import os
import unittest
from HtmlTestRunner import HTMLTestRunner
import app_demo1.config.config as config
#测试结果信息收集：

def run(casedir,testplan):
    workdir = os.path.join(config.BASE_DIR,"app_demo3")
    casedir = os.path.join(config.BASE_DIR,"app_demo3\\testcases")
    discover = unittest.defaultTestLoader.discover(casedir, pattern="ui_lianjia*.py", top_level_dir=None)
    reportfile = os.path.join(workdir, 'report','htmltestrunner.html')
    with open(reportfile,'wb') as f:
        runner = HTMLTestRunner(stream=f,
                                verbosity=2,
                                title='my report',
                                description='generated by htmltestrunner')
        all_result=runner.run(discover)

    return all_result

if __name__ == '__main__':
    all_result=run(1,2)
    for item in all_result.result:
        print(item)