# Generated by Django 2.2.5 on 2019-09-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=10)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('worktime', models.FloatField()),
                ('flag', models.BooleanField()),
                ('content', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=10)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254, verbose_name='邮件')),
                ('number1', models.IntegerField(blank=True, null=True)),
                ('number2', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=10)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254, verbose_name='邮件')),
            ],
        ),
    ]
