# Generated by Django 2.2.2 on 2019-09-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='number1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
