# Generated by Django 2.2.2 on 2019-09-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo1', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yang',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=10)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254, verbose_name='邮件')),
            ],
        ),
    ]
