# -*- coding: utf-8 -*-
from app_demo1.lib.api_test import Apiclient
from app_demo1.lib.tool import *
from app_demo1.lib.database_con import  DataManager
from app_demo1.lib.log_manager import LogManager
from app_demo1.config import config

class ApiRunner():
    def __init__(self,file,dbtable):
        self.all_cases = import_excel_data(file)
        self.table=dbtable
        self.logger=LogManager("api")

    def run(self):
        result=[]
        for case in self.all_cases[1:]:
            print(case)
            client = Apiclient(config_build("wuliu",case))
            re=client.test()
            re["case"]=case
            print(re)
            self._save_result(re)  #每执行完一条case就存储到数据库
            result.append(re)
        return result

    def _save_result(self,apiresult):
        db=DataManager()
        message =db.save_api_case(apiresult)
        if message != True:
            self.logger.error(message)


class UiRunner():
    def __init__(self):
        #self.logger = LogManager("system")
        pass

    #根据文件名匹配case
    def run_by_pattern(self,casedir,testplan):
        workdir = os.path.join(config.BASE_DIR,"app_demo3")
        casedir = os.path.join(config.BASE_DIR,"app_demo3\\testcases")
        discover = unittest.defaultTestLoader.discover(casedir, pattern="ui_lianjia*.py", top_level_dir=None)
        reportfile = os.path.join(workdir, 'report','htmltestrunner.html')
        with open(reportfile,'wb') as f:
            runner = HTMLTestRunner(stream=f,
                                    verbosity=2,
                                    title='my report',
                                    description='generated by htmltestrunner')
            all_result=runner.run(discover)

        return all_result

    #根据case名匹配case
    def run_by_casename(self,caselist):
        workdir = os.path.join(config.BASE_DIR,"app_demo3")
        caselist = ['lianjia.ui_lianjia_test_001.Base_t1.test_run3','lianjia.ui_lianjia_test_001.Base_t1.test_run']
        discover = unittest.TestLoader().loadTestsFromNames(caselist,module=None)
        reportfile = os.path.join(workdir, 'report','htmltestrunner.html')
        with open(reportfile,'wb') as f:
            runner = HTMLTestRunner(stream=f,
                                    verbosity=2,
                                    title='my report',
                                    description='generated by htmltestrunner')
            all_result=runner.run(discover)

        return all_result


if __name__=="__main__":
    cc=ApiPerformer(config.API_CASE["wuliu"],'rr')
    print(cc.run())