board:
    城市:
        type: xpath
        name:
        value: /html/body/div[1]/div/div[1]/span
    搜索框:
        type: id
        name:
        value: keyword-box
    搜索按钮:
        type: id
        name:
        value: findHouse
    找二手房:
        type: xpath
        name:
        value: /html/body/div[1]/div/div[5]/div[3]/div/div[1]/ul/li[1]/span
    找新房:
        type: xpath
        name:
        value: /html/body/div[1]/div/div[5]/div[3]/div/div[1]/ul/li[2]/span
city:
    搜索框:
        type: xpath
        name:
        value: /html/body/div[1]/div/div[2]/input
    搜索按钮:
        type: xpath
        name:
        value: /html/body/div[1]/div/div[2]/a
    搜索提示框:
        type: xpath
        name:
        value: //*[@id='city_sug']/ul/li/a
二手房在售:
    顶部菜单:
        type: xpath
        name:
        value: /html/body/div[1]/div/ul
    顶部菜单子节点:
        type: xpath
        name:
        value: /html/body/div[1]/div/ul/li
    菜单子项:
        type: xpath
        name:
        value: /html/body/div[1]/div/ul/li[%s]/a
    经纪人:
        type: xpath
        name:
        value: /html/body/div[1]/div/ul/li[8]/a
经纪人:
    搜索框:
        type: id
        name:
        value: keyword-box
    搜索按钮:
        type: xpath
        name:
        value: //*[@id="searchForm"]/button

